#!/bin/bash

set -e

# Setup Sources and Bootstrap APT

apt -y install \
	autotools-dev \
	libasound2-dev \
	libblas-dev \
	libboost-filesystem-dev \
	libboost-iostreams-dev \
	libboost-python-dev \
	libboost-serialization-dev \
	libboost-system-dev \
	libboost-test-dev \
	libboost-thread-dev \
	libbz2-dev \
	libc6-dev \
	libcairo2-dev \
	libcgal-dev \
	libclang-common-16-dev \
	libcurl4-openssl-dev \
	libdw-dev \
	libedit-dev \
	libeigen3-dev \
	libexpat1-dev \
	libffi-dev \
	libfftw3-dev \
	libfl-dev \
	libgcc-13-dev \
	libgettextpo-dev \
	libgirepository1.0-dev \
	libgit2-dev \
	libglu1-mesa-dev \
	libgmp-dev \
	libgoogle-perftools-dev \
	libgtk-3-dev \
	libgtk-4-dev \
	libhdf5-dev \
	libjpeg-dev \
	libjudy-dev \
	liblapack-dev \
	liblemon-dev \
	liblzma-dev \
	libmng-dev \
	libmpc-dev \
	libmpfr-dev \
	libncurses-dev \
	libomp-dev \
	libopenmpi-dev \
	libpcre2-dev \
	libpcre3-dev \
	libpolly-16-dev \
	libqhull-dev \
	libqt5charts5-dev \
	libqt5svg5-dev \
	libqt5xmlpatterns5-dev \
	libqt6svg6-dev \
	libre2-dev \
	libreadline-dev \
	libsm-dev \
	libsqlite3-dev \
	libssl-dev \
	libstdc++-11-dev \
	libsuitesparse-dev \
	libtinyxml-dev \
	libvtk9-dev \
	libvtk9-qt-dev \
	libwxgtk3.2-dev \
	libx11-dev \
	libx11-xcb-dev \
	libxaw7-dev \
	libxcb1-dev \
	libxext-dev \
	libxft-dev \
	libxml2-dev \
	libxpm-dev \
	libxrender-dev \
	libxslt-dev \
	libyaml-dev \
	libz-dev \
	libz3-dev \
	libzip-dev \
	libzstd-dev \
	llvm-16-dev \
	python3-dev \
	qtbase5-dev \
	qtbase5-dev-tools \
	qt6-base-dev \
	qt6-charts-dev \
	qt6-tools-dev \
	qt6-tools-dev-tools \
	qtmultimedia5-dev \
	qttools5-dev \
	ruby-dev \
	tcl-dev \
	tk-dev \
	uuid-dev \
	zlib1g-dev \
	automake \
	build-essential \
	clang-16 \
	clang-tools-16 \
	debhelper \
	dh-autoreconf \
	g++ \
	g++-13 \
	g++-13-aarch64-linux-gnu \
	g++-aarch64-linux-gnu \
	gcc \
	gcc-13 \
	gcc-13-aarch64-linux-gnu \
	gcc-aarch64-linux-gnu \
	gfortran \
	gfortran-13 \
	gfortran-13-aarch64-linux-gnu \
	gfortran-aarch64-linux-gnu \
	gnat \
	gnat-13 \
	gnat-13-aarch64-linux-gnu \
	gobject-introspection \
	gobject-introspection-bin \
	lcov
  