name: ci-docker-build

on: 
  workflow_dispatch:

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
    #  - name: Login to Docker Hub
    #    uses: docker/login-action@v3
    #    with:
    #      username: ${{ secrets.DOCKERHUB_USERNAME }}
    #      password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Print Folder Tree
        uses: jaywcjlove/github-action-folder-tree@main
        with:
          depth: 2
        
      - name: Validate build configuration
        uses: docker/build-push-action@v6
        with:
          call: check
          file: "./_build/Dockerfile"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: user/app:latest
          context: "./_build/" 
          file: "./_build/Dockerfile"
          sbom: true
          
